submit50:
  files: &submit50_files
    - !exclude "*"
    - !include "fixme2.py"
    - !include "weather.py"
    - !include "homework.py"
    - !include "conversion.py"
    - !require fixme2.py
    - !require weather.py
    - !require homework.py
    - !require conversions.py
    
  style: false

check50:
  files: *submit50_files